export const STATUS: Record<string, { label: string; color: string }> = {
  created:          { label: "Reçue",           color: "bg-slate-100 text-slate-600" },
  confirmed:        { label: "Acceptée",         color: "bg-blue-100 text-blue-700" },
  prepared:         { label: "Prête",            color: "bg-green-100 text-green-700" },
  delivered:        { label: "Livrée",           color: "bg-emerald-100 text-emerald-700" },
  cancelled:        { label: "Annulée",          color: "bg-red-100 text-red-600" },
  pending:          { label: "En attente",       color: "bg-yellow-100 text-yellow-700" },
  accepted:         { label: "Acceptée",         color: "bg-blue-100 text-blue-700" },
  preparing:        { label: "En préparation",   color: "bg-orange-100 text-orange-700" },
  ready:            { label: "Prête",            color: "bg-green-100 text-green-700" },
  READY_FOR_PICKUP: { label: "Prête",            color: "bg-green-100 text-green-700" },
  delivering:       { label: "En livraison",     color: "bg-indigo-100 text-indigo-700" },
  DELIVERING:       { label: "En livraison",     color: "bg-indigo-100 text-indigo-700" },
  DELIVERED:        { label: "Livrée",           color: "bg-emerald-100 text-emerald-700" },
  CANCELLED:        { label: "Annulée",          color: "bg-red-100 text-red-600" },
  refused:          { label: "Refusée",          color: "bg-red-100 text-red-600" },
  REFUSED:          { label: "Refusée",          color: "bg-red-100 text-red-600" },
};
